### ISSUE TITLE
Gradle Script Not Git

### ISSUE THREAD

**Issue by LingASDJ** [F-LTP/Radish_Pixel_Dungeon#1]
![2c2dcdae7c1af46857defe275f96c58b](https://github.com/F-LTP/Radish_Pixel_Dungeon/assets/70191651/2d59d11c-ba12-4b72-afee-bbcbf742b23d)

Your PD source code only provides Java and asset packages, without providing Gradle build scripts or build steps.

For PDs based on the GPLv3 open source protocol, this is fatal.

Moreover, if you are unable to properly save your Gradle file locally, and the project is lost, you will need to clone your own library and rebuild the Gradle environment.

**Comment by F-LTP** [comment]
Thanks. I have filled in the missing files.
